language: node_js
node_js:
  - '6.1'
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run build
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'

before_install:
  - openssl aes-256-cbc -K $encrypted_6a56805a113e_key -iv $encrypted_6a56805a113e_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "Travis-CI"
